name: Dependency Update

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Update dependencies
      run: |
        uv sync --upgrade
        uv lock --upgrade

    - name: Run tests
      run: |
        uv sync --group dev
        uv run pytest tests/ -v

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          This PR updates project dependencies to their latest versions.

          Changes:
          - Updated all dependencies to latest compatible versions
          - Regenerated uv.lock file
          - All tests are passing

          Please review the changes and merge if everything looks good.
        branch: dependency-updates
        delete-branch: true
